[package]
name = "autoclear-dispatch"
version = "0.1.0"
authors = ["jude-LafiteIII <judewrs@gmail.com>"]
edition = "2018"

[dependencies]
mysql = "14.2.0"
dotenv = "0.13.0"
reqwest = "0.9.5"
threadpool = "1.7.1"
serde = "*"
serde_json = "*"
serde_derive = "*"
